:leveloffset: +1
= Foreword

BHEL is the largest engineering and manufacturing organization in the Power, Industrial, transportation systems, transmission systems, renewables and services sectors. 
It has 16 manufacturing Units, 2 repair units, 4 power sector regions and 3 units for engineering and supply located in different parts of the country.

The company had entered into technical collaborations with national/international companies, which resulted in importing their design philosophies, drawing office practices, conventions, material grades leading to the usage of divergent practices. 
To optimize operations in terms of costs, quality and customer satisfaction it became essential that the divergent practices are rationalized and unified at the corporate level in order to lead to the vision of Atmanirbhar Bharat as envisaged by the company as the need of the hour. 
Leading engineering organizations of the world like GE, ABB, Siemens etc., have their own unified systems. 
Major Indian organizations like SAIL, BEL, IOCL, etc., also have their own unified systems. 
BHEL also has a strategy and system towards standardization and codification that has evolved over the years. 
This system has been giving tangible and intangible benefits to the company.

“One of the fundamental purposes of standardization and codification at the company level is the promotion of the profitability of the company. 
This promotion may have three aims. 
The first aim would be the standardization and codification of the company’s own products, components, materials, methods, etc., to improve the coordination of international operations constituting the quality loop.

The next aim will be to achieve the standardization and codification of goods or services produced inside the country or of those imported. 
This is to obtain lower prices, adequate quality and compliance with international procedures.

The third aim will be to achieve harmonization of customer requirements and those of authorities inside and outside the country in order to reduce the variety of the products”.